### PR TITLE
Reusing Existing Constructor for default case

### PR DESCRIPTION
**Pull request by deepanprabhu**

### CODE REVIEW

**Comment by deepanprabhu** [comment]
@doghouch ,
I think i might have more PRs,

**Comment by doghouch** [comment]
I don’t think that needs to be optimized — the old constructor will be entirely removed in the near future.

**Comment by deepanprabhu** [comment]
thanks, feel free to close this.
@doghouch ,

**Comment by doghouch** [comment]
All done - thanks again for your contributions :)

**Pull request closed without merging**
